image: codersakl/docker-alpine-gitftp:latest

pipelines:
  branches:
    develop:
    - step:
        name: Init
        script:
          - npm ci
    - step:
        name: Build
        script:
          - npm ci
          - npm run build
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - npm ci
          - npm run build
          - lftp -c "open -e 'mirror --reverse --delete --verbose ./$BUILD_DIR/ .' $FTP_DEV_USERNAME:$FTP_DEV_PASSWORD@$FTP_DEV_HOST"

    master:
      - step:
          name: Init
          script:
            - npm ci
      - step:
          name: Build
          script:
            - npm run build
      - step:
          name: Deploy to prod
          deployment: production
          trigger: manual
          script:
            - npm ci
            - npm run build
            - lftp -c "open -e 'mirror --reverse --delete --verbose ./$BUILD_DIR/ .' $FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST"
