image: codersakl/docker-alpine-gitftp:latest

pipelines:
  branches:
    master:
      - step:
          name: Init
          caches:
            - node
          script:
            - npm ci
      - step:
          name: Build
          caches:
            - node
            - $BUILD_DIR
          script:
            - npm run build
      - step:
          name: Deploy to prod
          deployment: production
          trigger: manual
          caches:
            - node
          script:
            - lftp -c "open -e 'mirror --reverse --delete --verbose ./$BUILD_DIR/ .' $FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST"
