image: codersakl/docker-alpine-gitftp:latest

pipelines:
  branches:
    develop:
    - step:
        name: Init
        caches:
          - node
        script:
          - npm install
    - step:
        name: Build
        caches:
          - node
        script:
          - npm run build
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - npm run build
          - lftp -c "open -e 'mirror --reverse --delete --verbose ./$BUILD_DIR/ .' $FTP_DEV_USERNAME:$FTP_DEV_PASSWORD@$FTP_DEV_HOST"

    master:
      - step:
          name: Init
          caches:
            - node
          script:
            - npm install
      - step:
          name: Build
          caches:
            - node
          script:
            - npm run build
      - step:
          name: Deploy to prod
          deployment: production
          trigger: manual
          script:
            - npm run build
            - lftp -c "open -e 'mirror --reverse --delete --verbose ./$BUILD_DIR/ .' $FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST"
